#!/bin/bash
# author Abdennour Toumi (https://github.com/abdennour)

dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )";
cd "${dir}" || exit
helm package redis-commander
helm repo index .
