name: Build and publish Docker image

on:
  push:
    branches: [thomastvedt/add-docker-versioning]

#  create:
#    tags:
#      - 'v*'
#    branches: [master, thomastvedt/add-docker-versioning]

env:
  DOCKER_FILE: 'Dockerfile'
  DOCKER_REGISTRY_ORG: 'thomastvedt'
  DOCKER_REGISTRY_IMAGE_NAME: 'redis-commander'
  DOCKER_REGISTRY: 'hub.docker.com'
  DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}

jobs:
  docker:
    name: Build and publish docker image
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Get latest tag
        id: tag
        run: |
          git fetch --prune --unshallow
          echo '::set-output name=latest::'$(git describe --tags $(git rev-list --tags --max-count=1))

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1.0.1

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v1.1.1
        with:
          buildkitd-flags: --debug

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{env.DOCKER_USERNAME}}
          password: ${{env.DOCKER_PASSWORD}}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.3.0
        with:
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{env.DOCKER_REGISTRY_ORG}}/${{ env.DOCKER_REGISTRY_IMAGE_NAME }}:${{steps.tag.outputs.latest}},
            ${{ env.DOCKER_REGISTRY }}/${{env.DOCKER_REGISTRY_ORG}}/${{ env.DOCKER_REGISTRY_IMAGE_NAME }}:latest
